### ISSUE TITLE
jtupdate to generate PDF files for schematics

### ISSUE THREAD

**Issue by jotego** [jotego/jtframe#100]
Lately, I have been deleting all files that are project *outputs* from the repositories lately. For instance, all MiSTer MRA and Pocket JSON files are gone now. The `jtupdate` utility creates RBF, MRA, JSON and other files in either the *release* folder in the repository or in the JTBIN repository. Note that the *release* folder is not added to git. It is just a local folder.

I had a problem doing this with schematics as KiCAD does not support automation for this. However, I found that the upcoming KiCAD version will have a command-line interface. I've tested it to generate schematics and it works like a charm:

`kicad-cli-nightly sch export pdf pingpong.kicad_sch`

Generates the PDF for a multisheet schematic perfectly. So schematic PDFs will be removed from the repositories too and incorporated into JTBIN.

This approach is much more convenient to users as they can refer to a single location (JTBIN) for the files they care about. It also help us to keep a clean, lean and consistent source repository, following modern CI practices. I'll modify jtupdate to generate schematic PDF files in `release/sch` and `$JTBIN/sch`. 

## Generate PDFs using jtframe

The jtframe utility will have a new *sch* command

`jtframe sch corename`

For example:

`jtframe sch pinpon`

will generate the schematic for Konami's Ping Pong (assuming you are in the **JTKICKER** repository)

Cores with more than one schematic will get all of them dumped to PDF
`jtframe sch kiwi`

will generate the schematics for Insector-X, Extermination, etc. (in the **JTBUBL** repo)

The top-level schematic must be named like the core, or like the subfolder in sch.

## Update all PDFs in a repository using jtupdate

By default jtupdate will generate schematics. The `--nosch` will skip this step. Schematics will be generated in `release/sch` or `$JTBIN/sch` depending on whether jtupdate was called using the `--git` option or not

## Tasks

- [x] Add the **sch** command to **jtframe**
- [x] Add a step to call `jtframe sch` in jtupdate
- [x] Remove PDF files from repositories
- [x] Update the README in JTBIN to explain where the schematics are
- [x] Update the README in core repositories
