### ISSUE TITLE
spinner support

### ISSUE THREAD

**Issue by jotego** [jotego/jtframe#75]
Requested by RetroShop.pt

The part sent by RetroShop is detected by linux as a controller with one axis. MiSTer maps it to a paddle controller.

So far, games in the JT spectrum expect a spinner, not a paddle. Spinners work like a mouse: inform of a variation whereas the paddle reports an absolute position.

## Cores using spinner
- JTMIDRES: jt4701
- JTCPS1: jt4701
- JTCPS2: jt4701 
- JTPANG: 7-bit (MSB signed -inverted-)

## jt4701

- Compatible with NEC uPD4701A
- 12-bit output, unsigned, rolls over, 2 axis
- three buttons
- Each axis is reset by the software

## Tasks
- [X] Provide dial input to game modules
- [x] Mix mouse buttons with regular buttons
- [x] Add sensitivity options to OSD

**Comment by jotego** [comment]
Completed in 4323b17
